
import java.util.List;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ylhaart
 */
public class View extends javax.swing.JFrame {

    Population po;
    List<Person> loadPersons;
    int currentIndex = 0;

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        po = new Population("UK");
        //Person pe = new Person();
        loadPersons = Person.loadPersons("people.txt");
        getPerson();
        previous.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        birth_place = new javax.swing.JTextField();
        birth_country = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edit_last_name = new javax.swing.JButton();
        edit_first_name = new javax.swing.JButton();
        edit_birth_place = new javax.swing.JButton();
        edit_birth_country = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        view = new javax.swing.JMenu();
        next = new javax.swing.JMenuItem();
        previous = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Exercise 2.3");

        jLabel1.setText("First name:");

        jLabel2.setText("Last name:");

        jLabel3.setText("Birth place:");

        birth_place.setToolTipText("");

        jLabel4.setText("Birth country:");

        edit_last_name.setText("Edit...");
        edit_last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_last_nameActionPerformed(evt);
            }
        });

        edit_first_name.setText("Edit...");
        edit_first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_first_nameActionPerformed(evt);
            }
        });

        edit_birth_place.setText("Edit...");
        edit_birth_place.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_birth_placeActionPerformed(evt);
            }
        });

        edit_birth_country.setText("Edit...");
        edit_birth_country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_birth_countryActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        view.setText("View");

        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        view.add(next);

        previous.setText("Previous");
        previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousActionPerformed(evt);
            }
        });
        view.add(previous);

        jMenuBar1.add(view);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(birth_country, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(birth_place, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(edit_last_name)
                    .addComponent(edit_first_name)
                    .addComponent(edit_birth_place)
                    .addComponent(edit_birth_country))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(first_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_first_name))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(last_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_last_name))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(birth_place, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_birth_place))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(birth_country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit_birth_country))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        currentIndex++;
        if (currentIndex == loadPersons.size() - 1) {
            next.setEnabled(false);
        } else if (currentIndex > 0) {
            previous.setEnabled(true);
        } else {
            next.setEnabled(true);
        }
        getPerson();

    }//GEN-LAST:event_nextActionPerformed

    private void previousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousActionPerformed
        currentIndex--;
        if (currentIndex == 0) {
            previous.setEnabled(false);
        } else if (currentIndex < loadPersons.size() - 1) {
            next.setEnabled(true);
        } else {
            previous.setEnabled(true);
        }
        getPerson();
    }//GEN-LAST:event_previousActionPerformed

    private void edit_first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_first_nameActionPerformed
        String r = JOptionPane.showInputDialog(this, "Edit first name:", "First name", JOptionPane.QUESTION_MESSAGE);
        if (r != null) {
//            first_name.setText(r);
            Person person = loadPersons.get(currentIndex);
            person.setFirstName(r);
            loadPersons.set(currentIndex, person);
            getPerson();
        }
    }//GEN-LAST:event_edit_first_nameActionPerformed

    private void edit_last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_last_nameActionPerformed
        String r = JOptionPane.showInputDialog(this, "Edit last name:", "Last name", JOptionPane.QUESTION_MESSAGE);
        if (r != null) {
//            last_name.setText(r);
            Person person = loadPersons.get(currentIndex);
            person.setLastName(r);
            loadPersons.set(currentIndex, person);
            getPerson();
        }
    }//GEN-LAST:event_edit_last_nameActionPerformed

    private void edit_birth_placeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_birth_placeActionPerformed
        String r = JOptionPane.showInputDialog(this, "Edit birth place:", "Birth place", JOptionPane.QUESTION_MESSAGE);
        if (r != null) {
            Person person = loadPersons.get(currentIndex);
            person.setBirthTown(r);
            loadPersons.set(currentIndex, person);
            getPerson();
        }
    }//GEN-LAST:event_edit_birth_placeActionPerformed

    private void edit_birth_countryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_birth_countryActionPerformed
        String r = JOptionPane.showInputDialog(this, "Edit birth country:", "Birth country", JOptionPane.QUESTION_MESSAGE);
        if (r != null) {
            Person person = loadPersons.get(currentIndex);
            person.setBirthCountry(r);
            loadPersons.set(currentIndex, person);
            getPerson();
        }
    }//GEN-LAST:event_edit_birth_countryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birth_country;
    private javax.swing.JTextField birth_place;
    private javax.swing.JButton edit_birth_country;
    private javax.swing.JButton edit_birth_place;
    private javax.swing.JButton edit_first_name;
    private javax.swing.JButton edit_last_name;
    private javax.swing.JMenuItem exit;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField last_name;
    private javax.swing.JMenuItem next;
    private javax.swing.JMenuItem previous;
    private javax.swing.JMenu view;
    // End of variables declaration//GEN-END:variables

    private void getPerson() {
        Person person = loadPersons.get(currentIndex);

        first_name.setText(person.firstName);
        last_name.setText(person.lastName);
        birth_place.setText(person.birthTown);
        birth_country.setText(person.birthCountry);
    }
}
